// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	banksList: () => typedError<unknown, string>(__TAURI_INVOKE("banks_list")),
	banksCreate: (name: string, description: string | null) => typedError<unknown, string>(__TAURI_INVOKE("banks_create", { name, description })),
	banksUpdate: (id: string, name: string | null, description: string | null) => typedError<unknown, string>(__TAURI_INVOKE("banks_update", { id, name, description })),
	banksRemove: (id: string) => typedError<unknown, string>(__TAURI_INVOKE("banks_remove", { id })),
	questionsList: (query: string | null, typeFilter: string | null, bankId: string | null, limit: number | null, offset: number | null) => typedError<unknown, string>(__TAURI_INVOKE("questions_list", { query, typeFilter, bankId, limit, offset })),
	questionsGet: (id: string) => typedError<unknown, string>(__TAURI_INVOKE("questions_get", { id })),
	questionsCreate: (data: unknown) => typedError<unknown, string>(__TAURI_INVOKE("questions_create", { data })),
	questionsUpdate: (id: string, data: unknown) => typedError<unknown, string>(__TAURI_INVOKE("questions_update", { id, data })),
	questionsRemove: (id: string) => typedError<unknown, string>(__TAURI_INVOKE("questions_remove", { id })),
	practicePool: (limit: number | null, typeFilter: string | null, bankId: string | null, ids: string[] | null) => typedError<unknown, string>(__TAURI_INVOKE("practice_pool", { limit, typeFilter, bankId, ids })),
	recordAnswer: (items: RecordItem[]) => typedError<unknown, string>(__TAURI_INVOKE("record_answer", { items })),
	reviewDue: (limit: number | null, bankId: string | null) => typedError<unknown, string>(__TAURI_INVOKE("review_due", { limit, bankId })),
	wrongList: (bankId: string | null, typeFilter: string | null, limit: number | null, offset: number | null, leaveAfterCorrect: number | null) => typedError<unknown, string>(__TAURI_INVOKE("wrong_list", { bankId, typeFilter, limit, offset, leaveAfterCorrect })),
	/**  错题本手动移出（幂等；不删练习记录故不影响统计；之后再答错会自动重回） */
	wrongDismiss: (questionId: string) => typedError<unknown, string>(__TAURI_INVOKE("wrong_dismiss", { questionId })),
	/**  全部练习统计：全量按天明细（倒序，上限）+ 按题型汇总（含平均用时） */
	recordsOverview: (limitDays: number | null) => typedError<unknown, string>(__TAURI_INVOKE("records_overview", { limitDays })),
	/**
	 *  批量导入：一次调用入库多题（文件导入用）。逐条独立成功/跳过/失败，可重入（库内 plain_text 完全一致视为重复跳过）。
	 *  返回 {batch_id, items:[{index,status:'inserted'|'duplicate'|'error',id?,message?}]}
	 */
	importQuestions: (items: unknown[], bankId: string | null) => typedError<unknown, string>(__TAURI_INVOKE("import_questions", { items, bankId })),
	reviewStats: (bankId: string | null) => typedError<unknown, string>(__TAURI_INVOKE("review_stats", { bankId })),
	exportDbjson: () => typedError<unknown, string>(__TAURI_INVOKE("export_dbjson")),
	/**  打开模板文件夹：返回 export/ path，前端 openPath 打开（模板只供查看示例） */
	openTemplatesDir: () => typedError<unknown, string>(__TAURI_INVOKE("open_templates_dir")),
	/**
	 *  打开数据根目录（app_data_dir 或便携 data/）：给用户一条手动备份的活路
	 *  （导出格式未定，备份只能靠拷目录）。同样后端直调 opener，理由同上。
	 */
	openDataDir: () => typedError<unknown, string>(__TAURI_INVOKE("open_data_dir")),
	assetsPut: (dataB64: string, mime: string, width: number | null, height: number | null) => typedError<unknown, string>(__TAURI_INVOKE("assets_put", { dataB64, mime, width, height })),
	assetsResolve: (shas: string[]) => typedError<unknown, string>(__TAURI_INVOKE("assets_resolve", { shas })),
	assetsGc: () => typedError<unknown, string>(__TAURI_INVOKE("assets_gc")),
	saveTextFile: (filename: string, content: string) => typedError<unknown, string>(__TAURI_INVOKE("save_text_file", { filename, content })),
	importDbjson: (path: string) => typedError<unknown, string>(__TAURI_INVOKE("import_dbjson", { path })),
	/**
	 *  是否便携模式（cc-switch 同款命令）：供前端展示“便携版”徽章、将来更新器门控用。
	 *  不经过 AppState 锁，纯路径判定。
	 */
	isPortableMode: () => typedError<unknown, string>(__TAURI_INVOKE("is_portable_mode")),
};

/* Types */
export type FsrsCard = {
	stability: number | null,
	difficulty: number | null,
	reps: number,
	lapses: number,
	state: number,
	learning_steps: number,
	scheduled_days: number | null,
	due_at: string,
	last_reviewed_at: string | null,
	last_result: string | null,
};

export type RecordItem = {
	question_id: string,
	mode: string,
	grade: string | null,
	elapsed_ms: number | null,
	detail: unknown | null,
	/**  前端算好的 FSRS 卡片状态（FSRS-6）；有则 UPSERT review_state，无则只写流水 */
	card: FsrsCard | null,
	/**  本次作答的 ReviewLog 快照（未来跑 FSRS 优化器的数据源，现在只写不读） */
	fsrs_log: unknown | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

